Implementation for faster-whisper
SillyTavern/SillyTavern-Extras pull request #247
Opened 2024-12-09 09:19 UTC by ArrangingFear56

Updates whisper(extras) to use faster-whisper instead of openAI-whisper, defaults to large-v3-turbo model, install CUDA 12 and cuDNN 8, then run `pip install -r whisperRequirements.txt` to finish installation.

2024-12-09 10:41 UTC, Cohee1207 commented on modules/speech_recognition/whisper_module.py
> -"""
Adding files via upload messes up the diff due to line endings mismatch. Please resubmit using proper authoring tools. Use GitHub Codespaces if you need an online environment.

2024-12-09 13:04 UTC, Cohee1207 requested changes

2024-12-09 13:04 UTC, Cohee1207 commented on modules/speech_recognition/whisper_module.py
> +from faster_whisper import WhisperModel
I would like it to give a choice between the regular whisper and faster_whisper. Requiring new dependencies for already existing users is not ideal. Either provide a command line option, or at least wrap the import in try/except.

2024-12-09 13:04 UTC, Cohee1207 commented on modules/speech_recognition/whisper_module.py
> +model = WhisperModel(model_size, device="cuda", compute_type="float16")
This binds the model to cuda. Consider the cases when cuda is not available or not desired (using ARM CPU / AMD GPU / wanting to converve VRAM).

2024-12-09 13:04 UTC, Cohee1207 commented on modules/speech_recognition/whisper_module.py
> +        segments, info = model.transcribe(RECORDING_FILE_PATH, beam_size=5)
Does it preserve the ability to set a language for the transcription? Automatic detection may lack accuracy.

2024-12-09 17:26 UTC, ArrangingFear56 commented on modules/speech_recognition/whisper_module.py
> +from faster_whisper import WhisperModel
now it is an argument to enable faster-whisper and defaults to the old module.

2024-12-09 17:28 UTC, ArrangingFear56 commented on modules/speech_recognition/whisper_module.py
> +model = WhisperModel(model_size, device="cuda", compute_type="float16")
added argument `--faster-whisper-cpu` to switch to cpu

2024-12-09 17:29 UTC, ArrangingFear56 commented on modules/speech_recognition/whisper_module.py
> +        segments, info = model.transcribe(RECORDING_FILE_PATH, beam_size=5)
It should, at least according to faster-whisper's original repo, difficult to test though.

2024-12-10 16:04 UTC, Cohee1207 commented on README.md
> +pip install -r fasterWhisperRequirements.txt
Please rename the file to match the rest of the requirements files (e.g. `requirements-faster-whisper.txt`)

2024-12-10 16:20 UTC, ArrangingFear56 commented on README.md
> +pip install -r fasterWhisperRequirements.txt
done

2024-12-10 16:21 UTC, Cohee1207 approved these changes
Tested. Works fine, thanks.

2024-12-10 16:23 UTC, merged